kind: pipeline
type: docker
name: hugo-to-s3

steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      AWS_REGION:
        from_secret: aws_region
      BUCKET:
        from_secret: s3_bucket_name
    commands:
      - hugo --minify --baseURL "https://my-restaurant-site-ccm-123456.s3.us-east-1.amazonaws.com/"

  - name: debug-list
    image: alpine:3.20
    commands:
      - ls -la
      - ls -la public | head -50
      -
  - name: upload-to-s3
    image: public.ecr.aws/aws-cli/aws-cli:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_REGION:
        from_secret: aws_region
      BUCKET:
        from_secret: s3_bucket_name
    commands:
      - set -euo pipefail
      - echo "Bucket=my-restaurant-site-ccm-123456  Region=us-east-1"
      - aws --version
      - aws sts get-caller-identity >/dev/null
      - aws s3 sync public/ "s3://my-restaurant-site-ccm-123456/" --region "us-east-1" --delete --cache-control "max-age=300"
      - aws s3 ls "s3://my-restaurant-site-ccm-123456/" --region "us-east-1" | head -20
    when:
      event: [ push ]
      branch: [ master ]




