kind: pipeline
type: docker
name: hugo-to-s3

steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      AWS_REGION:
        from_secret: aws_region
    commands:
      - hugo --minify --baseURL "http://$DRONE_REPO_OWNER.s3-website-$AWS_REGION.amazonaws.com/"

  - name: debug-list
    image: alpine:3.20
    commands:
      - ls -la
      - ls -la public | head -50

  - name: upload-to-s3
    image: public.ecr.aws/aws-cli/aws-cli:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_REGION:
        from_secret: aws_region
      BUCKET:
        from_secret: s3_bucket_name
    commands:
      - aws --version
        - aws sts get-caller-identity
        - aws s3 sync public/ "s3://${BUCKET}/" \
        --region "$AWS_REGION" \
        --delete \
        --acl public-read \
        --cache-control "max-age=300"
    when:
      event: [ push ]
      branch: [ master ]
