kind: pipeline
type: docker
name: hugo-to-s3

steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      AWS_REGION:
        from_secret: aws_region
    commands:
      - hugo --minify --baseURL "http://$DRONE_REPO_OWNER.s3-website-$AWS_REGION.amazonaws.com/"

  - name: debug-list
    image: alpine:3.20
    commands:
      - ls -la
      - ls -la public | head -50
      -
  - name: who-am-i
    image: public.ecr.aws/aws-cli/aws-cli:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_REGION:
        from_secret: aws_region
    commands:
      - aws --version
      - aws sts get-caller-identity || exit 1
      - aws s3 ls --region ${AWS_REGION}

  - name: upload-to-s3
    image: plugins/s3
    settings:
      bucket: my-restaurant-site-ccm-123456
      region:
        from_secret: aws_region
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      session_token:
        from_secret: aws_session_token
      source: public/**
      strip_prefix: public/
      target: /
      recursive: true
    when:
      event: [ push ]
      branch: [ master ]
