---
kind: pipeline
type: docker
name: hugo-to-s3

steps:
  - name: publish-to-s3
    image: amazon/aws-cli:2
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_REGION:
        from_secret: aws_region
      BUCKET: my-restaurant-site-ccm-123456  # <= remplace par le bucket
    commands:
      - echo "🚀 Upload vers S3 : $BUCKET"
      - aws s3 sync public/ "s3://${BUCKET}" --delete
      - aws s3 ls "s3://${BUCKET}" | head -5

trigger:
  event: [ push ]
  branch: [ master ]
