kind: pipeline
type: docker
name: hugo-to-s3

steps:
  - name: upload-to-s3
    image: plugins/s3
    settings:
      bucket: my-restaurant-site-ccm-123456
      region:
        from_secret: aws_region
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: public/**
      target: /
      strip_prefix: public/
      acl: public-read
      path_style: true
      recursive: true
    when:
      event:
        - push
      branch:
        - master
